### ISSUE TITLE
Expected server HTML to contain a matching <div> in <div>

### ISSUE THREAD

**Issue by nickmcmillan** [hector-del-rio/gatsby-plugin-loadable-components-ssr#1]
Firstly thanks for making this plugin.

I've found that the plugin works as expected when a project is built using `gatsby build`.

However whilst in development mode `gatsby develop` an error is logged to the console `Expected server HTML to contain a matching <div> in <div>`

I'd imagine this might be because in development mode there's no need for SSR, but the plugin is expecting it.

**Comment by hector-del-rio** [comment]
The error does not appear in my project, could you provide some context? 

Are you using `window` or `document` globals in your components?

**Comment by nickmcmillan** [comment]
I've created a reduced test case based on the Gatsby Default Starter;
https://github.com/nickmcmillan/gatsby-starter-default-with-gatsby-plugin-loadable-components-ssr

In `page-2.js` you'll see how I'm conditionally loading a component.
If you run the project in development mode you'll see the error logged to the console.

There are no references to `window` or `document`.

**Comment by Goosens** [comment]
I'm experiencing the same error. It looks like the problem lays with the render method being used in the `replaceHydrateFunction` in the `gatsby-browser.js`. When using `ReactDom.render` on the development build instead of the `ReactDom.hydrate` the error is gone.

A possible fix could be switching the render methods based on the type of build. For example:
```
const renderMethod = !!module.hot ? ReactDOM.render : ReactDOM.hydrate;
```
This will check if your build is using the Hot Module Replacement of Webpack (which `gatsby develop` uses) and based on that, switch the render method.

**Comment by nickmcmillan** [comment]
Just had a thought, since in production-mode React suppresses its handy console warnings & errors it's likely that this error is present in the production build too.

To verify this I'm trying to find whether its possible to force Gatsby to build using the development version of React. I found this but haven't had any luck yet https://github.com/facebook/react/issues/17499

**Comment by rsurjano** [comment]
> I've created a reduced test case based on the Gatsby Default Starter;
> https://github.com/nickmcmillan/gatsby-starter-default-with-gatsby-plugin-loadable-components-ssr
> 
> In `page-2.js` you'll see how I'm conditionally loading a component.
> If you run the project in development mode you'll see the error logged to the console.
> 
> There are no references to `window` or `document`.

Also I am getting the same error, is there a possible fix to mitigate such error?

**Comment by hector-del-rio** [comment]
Thanks @nickmcmillan for providing the reduced test case repo. Based on @Goosens suggestion, I created a fix now published in `v.1.0.8`.
