### ISSUE TITLE
"gatsby-plugin-loadable-components-ssr" threw an error while running the onPostBuild lifecycle

### ISSUE THREAD

**Issue by amkulkarni29** [hector-del-rio/gatsby-plugin-loadable-components-ssr#14]
Adding a config for gatsby-plugin-loadable-components-ssr in gatsby-config.js file throws this error in gatsby build. Works fine locally:

ENOENT: no such file or directory, unlink 'REPO_PATH/public/loadable-stats-build-javascript.json'

  39 | const onPostBuild = () => {
  40 |   // Clean after ourselves
  41 |   (0, _fs.unlinkSync)(_constants.statsPath);
     |                      ^
  42 | };
  43 |
  44 | exports.onPostBuild = onPostBuild;

Can someone help me out with this?

**Comment by graysonhicks** [comment]
This was fixed with #8 and is available on the `next` version by updating your package.json like this:

`"gatsby-plugin-loadable-components-ssr": "next"`

This will be released the soonest version bump.  Thanks!
