### ISSUE TITLE
Gatsby, Inc. Support

### ISSUE THREAD

**Issue by graysonhicks** [hector-del-rio/gatsby-plugin-loadable-components-ssr#15]
Hi @hector-del-rio !  We love this plugin at Gatsby, Inc. and would like to have access to the repo and npm org for maintenance and releases.  [Let us know if that's okay](mailto:support@gatsbyjs.com) and let's get it set up, thanks!

**Comment by KyleAMathews** [comment]
We'd love to help out! This is a great component that a lot of people benefit from.

**Comment by graysonhicks** [comment]
Thanks Hector!
