### ISSUE TITLE
Stopped working after building with Preact

### ISSUE THREAD

**Issue by valse** [hector-del-rio/gatsby-plugin-loadable-components-ssr#2]
Hi, I'm using your plugin and it works great but after adding the `gatsby-plugin-preact` to building with Preact, my `gatsby-image`s stopped working.

I made a demo simply installing both the plugin and you can see the image issue:
https://codesandbox.io/s/weathered-fire-26o6i

Thanks
valse

**Comment by hector-del-rio** [comment]
Hello, could yo specify what's the problem with the image?

<img width="728" alt="Screenshot 2020-03-03 at 11 14 50" src="https://user-images.githubusercontent.com/9391691/75760660-4da26580-5d40-11ea-8c92-f4837da62265.png">

**Comment by valse** [comment]
Hi @hector-del-rio... the Preact plugin works only on production build so you must execute `yarn build` and then `yarn serve` to see the site exposed on port 9000.

![image](https://user-images.githubusercontent.com/1492995/75774220-c78e1b00-5d4f-11ea-92e3-3cc63fedf267.png)

**Comment by hector-del-rio** [comment]
@valse The issue seems to be related to ReactDOM.hydrate, since changing it to ReactDOM.render works. 

`v2.0.0` adds the option `useHydrate` with which you can choose between using render or hydrate.
