### ISSUE TITLE
WebpackError: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by LekoArts** [hector-del-rio/gatsby-plugin-loadable-components-ssr#3]
Hi!

Thanks for the plugin, it certainly makes it easier than reading through their long docs :)

I'm using `@loadable/component` for my Minimal Blog theme on https://minimal-blog.lekoarts.de and was made aware of that the code blocks I use it for are missing in the RSS feed: https://github.com/LekoArts/gatsby-themes/issues/299

The cause I of course loadable and hence I tried out your plugin. Unfortunately I'm hitting an error with it:

```bash
 ERROR #95313

Building static HTML failed for path "/fantastic-beasts-and-where-to-find-them"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  65 |     // don't hoist over string (html) components
  66 |     if (objectPrototype) {
> 67 |       var inheritedComponent = getPrototypeOf(sourceComponent);
     | ^
  68 |
  69 |       if (inheritedComponent && inheritedComponent !== objectPrototype) {
  70 |         hoistNonReactStatics(targetComponent, inheritedComponent, blacklist);


  WebpackError: TypeError: Cannot convert undefined or null to object

  - hoist-non-react-statics.cjs.js:67 hoistNonReactStatics
    [gatsby-themes]/[hoist-non-react-statics]/dist/hoist-non-react-statics.cjs.js:67:1

  - loadable.esm.js:329 resolveComponent
    [gatsby-themes]/[@loadable]/component/dist/loadable.esm.js:329:23

  - loadable.esm.js:186 InnerLoadable.loadSync
    [gatsby-themes]/[@loadable]/component/dist/loadable.esm.js:186:1

  - loadable.esm.js:123 new InnerLoadable
    [gatsby-themes]/[@loadable]/component/dist/loadable.esm.js:123:1

  - cache.esm.js:3 Promise._resolveFromExecutor
    [gatsby-themes]/[@emotion]/cache/dist/cache.esm.js:3:49
```

You can reproduce this by cloning https://github.com/LekoArts/gatsby-themes/tree/minimal-code-ssr (and switching to the minimal-code-ssr branch) and running `yarn workspace minimal-blog build`.

This runs the project `examples/minimal-blog` which in turn uses `packages/gatsby-theme-minimal-blog`. The Code component is located here: https://github.com/LekoArts/gatsby-themes/blob/minimal-code-ssr/themes/gatsby-theme-minimal-blog/src/components/code.tsx

Sadly I'm not too familiar with loadable so would appreciate any help in solving this. Thanks!

**Comment by hector-del-rio** [comment]
I took a look at the code and checked it out locally. In `code.tsx` I don't think you are using `loadable-components` according to the documentation in their page. Please refer to [their docs](https://loadable-components.com/docs/getting-started/) for more info.

I will close this issue since it is not related to this project.

**Comment by LekoArts** [comment]
Eh, the code is fine and works as expected. I had to use a more difficult setup due to the default export and named export of `prism-react-renderer`. If I remove your plugin it works fine.

So unfortunately your comment is not really helpful regarding my original issue.
